// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqPKTYA7VC1TaMuvZ_xXbktJaUiSIv6OA',
    appId: '1:465783089846:android:21aa4a053cbee82937d417',
    messagingSenderId: '465783089846',
    projectId: 'communify-acda2',
    databaseURL: 'https://communify-acda2-default-rtdb.firebaseio.com',
    storageBucket: 'communify-acda2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCBzCAZ0lS2rxLmvOjSzsLzNMeZtCa8OQ',
    appId: '1:465783089846:ios:ed1d879f1b75d44237d417',
    messagingSenderId: '465783089846',
    projectId: 'communify-acda2',
    databaseURL: 'https://communify-acda2-default-rtdb.firebaseio.com',
    storageBucket: 'communify-acda2.appspot.com',
    iosClientId: '465783089846-m08rf798jo3qjroa866ulggnoda5pkc3.apps.googleusercontent.com',
    iosBundleId: 'com.example.communify',
  );
}
